"""Stage: task spec -> Demonstration skeleton with an LLM-written procedure."""

from __future__ import annotations

from datetime import date
from pathlib import Path

from PIL import Image

from interactive_interfaces.models.base import LLMClient
from interactive_interfaces.schemas.demonstration import Demonstration, Provenance
from interactive_interfaces.utils.io import make_placeholder_image, parse_json_response
from interactive_interfaces.utils.logging import call_context
from interactive_interfaces.utils.prompts import render


def create_demo(task: dict, *, out_dir: Path | str, llm: LLMClient) -> Demonstration:
    """Build a demonstration skeleton: initial image + LLM-written procedure.

    ``task`` is a parsed task spec from ``data/tasks/``. The initial image is
    copied from the task's seed photo if present, else a clearly-marked
    placeholder is synthesized. The demonstration's ``steps`` stay empty -
    decomposition is a separate stage.
    """
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    task_id = task["task_id"]
    domain = task["domain"]
    goal = task["user_goal"]

    initial_path = out_dir / "initial.png"
    seed = task.get("initial_image_path")
    if seed and Path(seed).exists():
        Image.open(seed).convert("RGB").save(initial_path)
    else:
        make_placeholder_image(initial_path, f"{task_id}  initial state", f"goal: {goal}")

    prompt = render(
        "procedure_from_task",
        user_goal=goal,
        domain=domain,
        initial_state_description=task.get("initial_state_description", ""),
    )
    with call_context("create_demo", task_id=task_id):
        raw = llm.generate(prompt=prompt)
    parsed = parse_json_response(raw)

    return Demonstration(
        task_id=task_id,
        domain=domain,
        user_goal=goal,
        initial_image_path=initial_path,
        initial_state_description=task.get("initial_state_description"),
        procedure_text="\n".join(parsed.get("procedure", [])),
        source_type="model_generated",
        provenance=Provenance(
            author="mock pipeline",
            date=date.today().isoformat(),
            notes=f"Generated by the Stage 1 mock pipeline (llm={llm.name}).",
        ),
        safety_notes=parsed.get("safety", []),
        tags=[domain, "mock"],
    )
